spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wjz520
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file: logs/log_dev.log
  level:
      root: info
      com.wjz.blog: debug
